---
title: "causes"
author: "Theo Rashid"
date: "20/03/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## cause rates

```{r imports}
library(here)
library(tidyverse)
library(abind)
library(cowplot)
library(colorspace)
library(scales)
library(geojsonsf)
library(sf)
library(ggridges)
library(treemap)

source(here("thesis_analysis", "theme_thesis.R"))
source(here("thesis_analysis", "palette_thesis.R"))
source(here("thesis_analysis", "skeletons.R"))
```

## data

```{r data}
args <- lst(region = "LAD", model = "car_as_at")

sexes <- c("female", "male")

e0 <- abind(
  read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_female_",
        args$model,
        "_e0.rds"
      )
    )
  ),
  read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_male_",
        args$model,
        "_e0.rds"
      )
    )
  ),
  along = 0,
  new.names = sexes
)

dimnames(e0) <- list(
  sex = dimnames(e0)[[1]],
  year = dimnames(e0)[[2]],
  LAD2020 = dimnames(e0)[[3]],
  sample = dimnames(e0)[[4]]
)

cause_q <- lst(
  male = read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_male_",
        args$model,
        "_causes_80q0.rds"
      )
    )
  ),
  female = read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_female_",
        args$model,
        "_causes_80q0.rds"
      )
    )
  )
)
```

```{r covariate and shape data}
shape <- geojson_sf(here("data", "covariates", "LAD2020_ENG_BGC.geojson"))
n_lad <- length(unique(shape$LAD2020))
```

```{r calculate median e0 in over time}
median_e0 <- apply(
  X = e0,
  MARGIN = c(1, 2, 3),
  FUN = median
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(`e0` = Freq) |>
  mutate(year = as.integer(year)) |>
  arrange()
```

```{r calculate median e0 change 2002-2019}
median_e0_change <- apply(
  X = e0[, "2019", , ] - e0[, "2010", , ],
  MARGIN = c(1, 2),
  FUN = median
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(de0 = Freq)
```

```{r median of changes}
median_e0 |>
  filter(year == 2010 | year == 2019) |>
  group_by(sex, LAD2020) |>
  summarise(de0 = diff(e0)) |>
  arrange(de0)
```

```{r calculate median 80q0 over time}
median_q <- lst()
for (s in c("male", "female")) {
  median_q[[s]] <- apply(
    X = cause_q[[s]],
    MARGIN = c(1, 2, 4),
    FUN = median
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(`80q0` = Freq) |>
    mutate(year = as.integer(year)) |>
    arrange()
}
```

```{r calculate median 80q0 relative change 2002-2019}
median_q_rel_change <- lst()
for (s in c("male", "female")) {
  median_q_rel_change[[s]] <- apply(
    X = (cause_q[[s]]["2019", , , ] - cause_q[[s]]["2002", , , ]) / cause_q[[s]]["2002", , , ],
    MARGIN = c(1, 3),
    FUN = median
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(d80q0 = Freq)
}
```

```{r quantile q}
quantile_q <- lst()
for (s in c("male", "female")) {
  quantile_q[[s]] <- apply(
    X = cause_q[[s]][c("2002", "2019"), , , ],
    MARGIN = c(1, 2, 4),
    FUN = quantile,
    p = c(0.025, 0.5, 0.975)
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(quantile = Var1, `80q0` = Freq) |>
    arrange() |>
    pivot_wider(names_from = quantile, values_from = `80q0`)
}
```

```{r probability of death range}
quantile_q |>
  bind_rows(.id = "sex") |>
  filter(year == 2019) |>
  filter(sex == "male") |>
  filter(cause == "All other cancers") |>
  arrange(-`50%`)
```

```{r inequality probability of death}
quantile_q |>
  pluck("female") |>
  filter(year == 2019) |>
  group_by(cause) |>
  summarise(
    max_min = max(`50%`) / min(`50%`),
    q90_q10 = quantile(`50%`, 0.9) / quantile(`50%`, 0.1)
  )
```

```{r percentage relative changes}
s <- "female"
apply(
  X = (cause_q[[s]]["2019", , , ] - cause_q[[s]]["2002", , , ]) * 100 / cause_q[[s]]["2002", , , ],
  MARGIN = c(1, 3),
  FUN = quantile,
  p = c(0.025, 0.5, 0.975)
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(quantile = Var1, `rel_change` = Freq) |>
  arrange() |>
  pivot_wider(names_from = quantile, values_from = `rel_change`) |>
  filter(cause == "Chronic obstructive pulmonary disease") |>
  arrange(-`50%`)
```

## treemap

```{r cause names}
cause_names <- tribble(
  ~cause, ~group, ~cause_lab, ~type, ~which_sex,
  "Trachea bronchus lung cancers", "Trachea, bronchus, lung cancers", "Trachea, bronchus, lung cancers", "cancer", "both",
  "Colon and rectum cancers", "Colon and rectum cancers", "Colorectal cancer", "cancer", "both",
  "Breast cancer", "Breast cancer", "Breast cancer", "cancer", "female",
  "Ovary cancer", "Ovary cancer", "Ovarian cancer", "cancer", "female",
  "Oesophagus cancer", "Oesophagus cancer", "Oesophageal cancer", "cancer", "male",
  "Prostate cancer", "Prostate cancer", "Prostate cancer", "cancer", "male",
  "Pancreas cancer", "Pancreas cancer", "Pancreatic cancer", "cancer", "female",
  "Lymphomas multiple myeloma", "Lymphomas, multiple myeloma", "Lymphomas, multiple myeloma", "cancer", "both",
  "All other cancers", "All other cancers", "All other cancers", "cancer", "both",
  "Ischaemic heart disease", "Ischaemic heart disease", "Ischaemic heart disease", "CVD", "both",
  "Cerebrovascular disease", "Cerebrovascular disease", "Stroke", "CVD", "both",
  "All other CVD", "All other CVD", "All other CVD", "CVD", "both",
  "Alzheimer and other dementias", "Alzheimer and other dementias", "Alzheimer's and other dementias", "NCD", "both",
  "Chronic obstructive pulmonary disease", "Chronic obstructive pulmonary disease", "COPD", "NCD", "both",
  "Cirrhosis of the liver", "Cirrhosis of the liver", "Liver cirrhosis", "NCD", "male",
  "Diabetes mellitus nephritis and nephrosis", "Diabetes mellitus, nephritis and nephrosis", "Diabetes", "NCD", "both",
  "All other NCD", "All other NCD", "All other NCD", "NCD", "both",
  "Lower respiratory infections", "Lower respiratory infections", "Lower respiratory infections", "GBD Group 1", "both",
  "All other infections maternal perinatal and nutritional conditions",
  "All other infections, maternal, perinatal and nutritional conditions",
  "All other IMPN",
  "GBD Group 1", "both",
  "External causes", "External causes", "Injuries", "Injuries", "both"
)
```

```{r tree map}
tm_df <- read_csv(here("data", "eda", "deaths_eng_cs.csv")) |>
  mutate(sex = recode(sex, `1` = "men", `2` = "women")) |>
  left_join(cause_names)

p <- tm_df |>
  mutate(
    lab = str_c(
      cause_lab,
      "\n",
      format(deaths, big.mark = ",")
      # " (",
      # format(round(deaths_prop, 1), nsmall = 1),
      # "%)"
    )
  ) |>
  treemap(
    index = c("sex", "lab"),
    type = "categorical",
    vSize = "deaths",
    vColor = "type",
    palette = cause_group_pal,
    fontsize.labels = 10,
    fontsize.title = 0,
    position.legend = "none",
    bg.labels = 0,
    align.labels = list(
      c("left", "top"),
      c("right", "bottom")
    ),
  )

quartz.save(
  here(
    "thesis_analysis",
    "causes",
    "figures",
    "treemap.pdf"
  ),
  type = "pdf"
)
```

## maps of 80q0

Maps of 80q0 in 2019 and d80q0 2002-19.
```{r map 80q0}
for (s in sexes) {
  cause_list <- cause_names |>
    filter(which_sex == "both" | which_sex == s) |>
    pull(cause)
  for (disease in cause_list) {
    print(disease)
    disease_label <- cause_names |>
      filter(cause == disease) |>
      pull(cause_lab)
    map <- shape |>
      left_join(
        median_q |>
          pluck(s) |>
          filter(year == 2019) |>
          filter(cause == disease) |>
          mutate(LAD2020 = LAD)
      ) |>
      ggplot(aes(fill = `80q0`)) +
      map_skeleton +
      scale_fill_continuous_sequential(
        palette = "Reds",
        name = ""
      )

    p <- median_q |>
      pluck(s) |>
      filter(year == 2019) |>
      filter(cause == disease) |>
      ggplot(aes(x = `80q0`, y = 1, fill = after_stat(x))) +
      ridge_skeleton +
      scale_fill_continuous_sequential(
        palette = "Reds",
        name = str_c("Probability of dying from\n", disease_label),
        breaks = breaks_pretty(n = 3)
      )

    range_change <- median_q_rel_change |>
      pluck(s) |>
      filter(cause == disease) |>
      pull(d80q0) |>
      range() |>
      sign() |>
      sum()

    if (range_change == 0) {
      change_mp <- 0
    } else if (range_change < 0) {
      change_mp <- median_q_rel_change |>
        pluck(s) |>
        filter(cause == disease) |>
        pull(d80q0) |>
        max()
    } else {
      change_mp <- median_q_rel_change |>
        pluck(s) |>
        filter(cause == disease) |>
        pull(d80q0) |>
        min()
    }

    map_change <- shape |>
      left_join(
        median_q_rel_change |>
          pluck(s) |>
          filter(cause == disease) |>
          mutate(LAD2020 = LAD)
      ) |>
      ggplot(aes(fill = `d80q0`)) +
      map_skeleton +
      scale_fill_continuous_divergingx(
        palette = "Geyser",
        mid = change_mp,
        name = "",
        labels = percent
      )

    p_change <- median_q_rel_change |>
      pluck(s) |>
      filter(cause == disease) |>
      ggplot(aes(x = `d80q0`, y = 1, fill = after_stat(x))) +
      ridge_skeleton +
      scale_fill_continuous_divergingx(
        palette = "Geyser",
        mid = change_mp,
        name = str_c("Change in probability for\n", disease_label),
        labels = percent,
        breaks = breaks_pretty(n = 3)
      )

    grid <- plot_grid(map, map_change)

    grid <- ggdraw(grid) +
      draw_plot(p, -0.35, -0.15, scale = 0.11) +
      draw_plot(p_change, 0.15, -0.15, scale = 0.11)

    save_plot(
      here(
        "thesis_analysis",
        "causes",
        "figures",
        str_c(s, "_map_", str_replace_all(disease, " ", "_"), ".pdf")
      ),
      grid
    )
  }
}
```

## cause decomposition

```{r decomposition 2002-19}
for (s in sexes) {
  if (s == "female") id <- 2 else id <- 1
  for (y1 in c(2002, 2010)) {
    for (y2 in c(2010, 2019)) {
      if (y1 != y2) {
        e0_decompose <- read_rds(
          here(
            "data",
            "life_table",
            str_c(
              args$region,
              "_",
              s,
              "_",
              args$model,
              "_e0_decompose",
              y1,
              y2,
              ".rds"
            )
          )
        )

        e0_change <- e0_decompose |>
          as.data.frame.table(stringsAsFactors = FALSE) |>
          as_tibble() |>
          rename(Dx = Freq) |>
          group_by(LAD) |>
          summarise(de0 = sum(Dx)) |>
          arrange(de0)

        p_e0_change <- e0_change |>
          mutate(LAD = factor(LAD, levels = e0_change$LAD)) |>
          ggplot(aes(x = de0, y = LAD)) +
          geom_vline(xintercept = 0, linewidth = 0.1, colour = "#403f3f9b") +
          geom_segment(aes(yend = LAD, x = 0, xend = de0), linewidth = 0.1, colour = "#CCCCCC", alpha = 0.4) +
          geom_point(color = sex_pal[id], size = 0.1) +
          labs(x = str_c("Life expectancy change\n", y1, "-", y2), y = "") +
          theme_thesis() +
          theme(
            axis.title.x = element_text(size = 4, vjust = +40),
            axis.ticks.y = element_blank(),
            axis.text.y = element_blank(),
            axis.line.y = element_blank()
          )

        p_decompose <- e0_decompose |>
          as.data.frame.table(stringsAsFactors = FALSE) |>
          as_tibble() |>
          rename(Dx = Freq) |>
          mutate(LAD = factor(LAD, levels = e0_change$LAD)) |>
          left_join(cause_names) |>
          mutate(cause_lab = factor(str_wrap(cause_lab, 18), levels = str_wrap(cause_names$cause_lab, 18))) |>
          ggplot(aes(x = cause_lab, y = LAD, fill = Dx)) +
          geom_tile(colour = NA) +
          scale_fill_continuous_divergingx(
            palette = "TealRose",
            rev = TRUE,
            mid = 0,
            p1 = 1.0,
            p2 = 0.7,
            h1 = 240,
            l1 = 40,
            p3 = 1.8,
            p4 = 0.7,
            name = "Contribution to change\nin life expectancy (years)",
            breaks = breaks_pretty(n = 5)
          ) +
          labs(x = "", y = "") +
          theme_thesis() +
          theme(
            axis.ticks.y = element_blank(),
            axis.text.y = element_blank(),
            axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
            legend.direction = "horizontal",
            legend.key.width = unit(12, units = "pt"),
            legend.key.height = unit(4, units = "pt"),
            legend.text = element_text(size = 4),
            legend.title = element_text(
              size = 4,
              face = "bold"
            )
          ) +
          guides(
            fill = guide_colorbar(
              title.position = "top",
              title.hjust = 0
            )
          )

        p_jitter <- e0_decompose |>
          as.data.frame.table(stringsAsFactors = FALSE) |>
          as_tibble() |>
          rename(Dx = Freq) |>
          left_join(cause_names) |>
          mutate(cause_lab = factor(cause_lab, levels = cause_names$cause_lab)) |>
          ggplot(aes(x = cause_lab, y = Dx, colour = Dx)) +
          geom_hline(yintercept = 0, linewidth = 0.1, colour = "#403f3f9b") +
          geom_jitter(size = 0.1, alpha = 0.4) +
          scale_colour_continuous_divergingx(
            palette = "TealRose",
            rev = TRUE,
            mid = 0,
            p1 = 1.0,
            p2 = 0.7,
            h1 = 240,
            l1 = 40,
            p3 = 1.8,
            p4 = 0.7,
          ) +
          labs(x = "", y = "Contribution to change in life expectancy (years)") +
          theme_thesis() +
          theme(
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank(),
            axis.line.x = element_blank(),
            axis.title.y = element_text(size = 4),
            legend.position = "none"
          )

        if (!(y1 == 2002 && y2 == 2019)) {
          if (s == "female") {
            p_jitter <- p_jitter + lims(y = c(-1.1, 1.2))
          } else {
            p_jitter <- p_jitter + lims(y = c(-1.1, 2.4))
          }
        }

        legend <- get_legend(p_decompose)

        grid <- plot_grid(
          NULL, NULL, p_jitter,
          NULL, NULL, NULL,
          p_e0_change, NULL, p_decompose + theme(legend.position = "none"),
          ncol = 3,
          rel_heights = c(5, -1.5, 10),
          rel_widths = c(1.4, -0.4, 4),
          align = "vh"
        ) +
          draw_grob(legend, 0.38, 0.26, 0.1, 1)

        save_plot(
          here(
            "thesis_analysis",
            "causes",
            "figures",
            str_c(s, "_decompose_", y1, "_", y2, ".pdf")
          ),
          grid,
          base_height = 7.00,
          base_width = 3.71
        )
      }
    }
  }
}
```

```{r decomposition data}
for (s in sexes) {
  if (s == "female") id <- 2 else id <- 1
  for (y1 in c(2002, 2010)) {
    for (y2 in c(2010, 2019)) {
      if (y1 != y2) {
        print(str_c(s, " ", y1, "-", y2))
        e0_decompose <- read_rds(
          here(
            "data",
            "life_table",
            str_c(
              args$region,
              "_",
              s,
              "_",
              args$model,
              "_e0_decompose",
              y1,
              y2,
              ".rds"
            )
          )
        )
        print(
          e0_change <- e0_decompose |>
            as.data.frame.table(stringsAsFactors = FALSE) |>
            as_tibble() |>
            rename(Dx = Freq) |>
            group_by(LAD) |>
            summarise(de0 = sum(Dx)) |>
            arrange(de0)
        )

        print(
          e0_decompose |>
            as.data.frame.table(stringsAsFactors = FALSE) |>
            as_tibble() |>
            rename(Dx = Freq) |>
            group_by(cause) |>
            summarise(
              min = min(Dx),
              max = max(Dx),
              max_min = max(Dx) - min(Dx),
              q90_q10 = quantile(Dx, 0.9) - quantile(Dx, 0.1)
            ) |>
            arrange(q90_q10)
        )
      }
    }
  }
}
```

```{r decomposition top district}
for (s in sexes) {
  if (s == "female") id <- 2 else id <- 1
  e0_decompose <- read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_",
        s,
        "_",
        args$model,
        "_e0_decompose_inequality2019",
        ".rds"
      )
    )
  )

  # contribution to inequality at top district is NaN
  e0_decompose[is.na(e0_decompose)] <- 0

  e0_diff <- e0_decompose |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(Dx = Freq) |>
    group_by(LAD) |>
    summarise(de0 = sum(Dx)) |>
    arrange(de0)

  p_e0_diff <- e0_diff |>
    mutate(LAD = factor(LAD, levels = e0_diff$LAD)) |>
    ggplot(aes(x = de0, y = LAD)) +
    geom_vline(xintercept = 0, linewidth = 0.1, colour = "#403f3f9b") +
    geom_segment(aes(yend = LAD, x = 0, xend = de0), linewidth = 0.1, colour = "#CCCCCC", alpha = 0.4) +
    geom_point(color = sex_pal[id], size = 0.1) +
    labs(x = str_c("Life expectancy difference\n", "in 2019"), y = "") +
    theme_thesis() +
    theme(
      axis.title.x = element_text(size = 4, vjust = +40),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.line.y = element_blank()
    )

  p_decompose <- e0_decompose |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(Dx = Freq) |>
    mutate(LAD = factor(LAD, levels = e0_diff$LAD)) |>
    left_join(cause_names) |>
    mutate(cause_lab = factor(str_wrap(cause_lab, 18), levels = str_wrap(cause_names$cause_lab, 18))) |>
    ggplot(aes(x = cause_lab, y = LAD, fill = Dx)) +
    geom_tile(colour = NA) +
    scale_fill_continuous_divergingx(
      palette = "TealRose",
      rev = TRUE,
      mid = 0,
      p1 = 1.0,
      p2 = 0.7,
      h1 = 240,
      l1 = 40,
      p3 = 1.8,
      p4 = 0.7,
      name = "Contribution to\nlife expectancy inequality (years)",
      breaks = breaks_pretty(n = 5)
    ) +
    labs(x = "", y = "") +
    theme_thesis() +
    theme(
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      legend.direction = "horizontal",
      legend.key.width = unit(12, units = "pt"),
      legend.key.height = unit(4, units = "pt"),
      legend.text = element_text(size = 4),
      legend.title = element_text(
        size = 4,
        face = "bold"
      )
    ) +
    guides(
      fill = guide_colorbar(
        title.position = "top",
        title.hjust = 0
      )
    )

  p_jitter <- e0_decompose |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(Dx = Freq) |>
    left_join(cause_names) |>
    mutate(cause_lab = factor(cause_lab, levels = cause_names$cause_lab)) |>
    ggplot(aes(x = cause_lab, y = Dx, colour = Dx)) +
    geom_hline(yintercept = 0, linewidth = 0.1, colour = "#403f3f9b") +
    geom_jitter(size = 0.1, alpha = 0.4) +
    scale_colour_continuous_divergingx(
      palette = "TealRose",
      rev = TRUE,
      mid = 0,
      p1 = 1.0,
      p2 = 0.7,
      h1 = 240,
      l1 = 40,
      p3 = 1.8,
      p4 = 0.7,
    ) +
    labs(x = "", y = "Contribution to life expectancy inequality (years)") +
    lims(y = c(-0.18, 2.75)) +
    theme_thesis() +
    theme(
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank(),
      axis.line.x = element_blank(),
      axis.title.y = element_text(size = 4),
      legend.position = "none"
    )

  legend <- get_legend(p_decompose)

  grid <- plot_grid(
    NULL, NULL, p_jitter,
    NULL, NULL, NULL,
    p_e0_diff, NULL, p_decompose + theme(legend.position = "none"),
    ncol = 3,
    rel_heights = c(5, -1.5, 10),
    rel_widths = c(1.4, -0.2, 4),
    align = "vh"
  ) +
    draw_grob(legend, 0.12, 0.255, 0.1, 1)

  save_plot(
    here(
      "thesis_analysis",
      "causes",
      "figures",
      str_c(s, "_decompose_inequality_2019", ".pdf")
    ),
    grid,
    base_height = 7.00,
    base_width = 3.71
  )
}
```
