---
title: "cancers"
author: "Theo Rashid"
date: "19/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## cause rates

```{r imports}
library(here)
library(tidyverse)
library(cowplot)
library(colorspace)
library(scales)
library(geojsonsf)
library(sf)
library(ggridges)
library(GGally)
library(treemap)

source(here("thesis_analysis", "theme_thesis.R"))
source(here("thesis_analysis", "palette_thesis.R"))
source(here("thesis_analysis", "skeletons.R"))
```

## data

```{r data}
args <- lst(region = "LAD", model = "car_as_at")

cause_q <- lst(
  male = read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_male_",
        args$model,
        "_cancers_80q0.rds"
      )
    )
  ),
  female = read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_female_",
        args$model,
        "_cancers_80q0.rds"
      )
    )
  )
)

cause_q_all_cancers <- lst(
  male = read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_male_",
        args$model,
        "_All_cancers_80q0.rds"
      )
    )
  ),
  female = read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_female_",
        args$model,
        "_All_cancers_80q0.rds"
      )
    )
  )
)

for (s in c("male", "female")) {
  print(
    cor(
      apply(
        X = cause_q[[s]],
        MARGIN = c(1, 2, 4),
        FUN = median
      )[, , "All cancers"] |>
        as.numeric(),
      apply(
        X = cause_q_all_cancers[[s]],
        MARGIN = c(1, 2),
        FUN = median
      ) |>
        as.numeric()
    )
  )

  cause_q[[s]][, , , "All cancers"] <- cause_q_all_cancers[[s]]
}
```

```{r covariate and shape data}
shape <- geojson_sf(here("data", "covariates", "LAD2020_ENG_BGC.geojson"))

cause_list <- lst(
  male = c(
    "Trachea bronchus lung cancers",
    "Prostate cancer",
    "Colon and rectum cancers",
    "Oesophagus cancer",
    "Lymphomas multiple myeloma",
    "Pancreas cancer",
    "Bladder cancer",
    "Stomach cancer",
    "Leukaemia",
    "Liver cancer",
    "All other cancers",
    "All cancers"
  ),
  female = c(
    "Trachea bronchus lung cancers",
    "Breast cancer",
    "Colon and rectum cancers",
    "Pancreas cancer",
    "Ovary cancer",
    "Lymphomas multiple myeloma",
    "Oesophagus cancer",
    "Leukaemia",
    "Corpus uteri cancer",
    "Stomach cancer",
    "All other cancers",
    "All cancers"
  )
)

imd <- read_csv(here("data", "covariates", "IMD_LAD2020_2019.csv")) |>
  mutate(`income rank` = rank(`income score`))

lookup <- read_csv(
  here(
    "data",
    "covariates",
    "LSOA_MSOA_LAD_GOR_CTRY_lookup.csv"
  )
) |>
  select(LAD2020, LAD2020NM, GOR2011, GOR2011NM) |>
  distinct() |>
  arrange(LAD2020)

n_lad <- length(unique(lookup$LAD2020NM))

regions <- c(
  "North East",
  "North West",
  "Yorkshire and The Humber",
  "East Midlands",
  "West Midlands",
  "East of England",
  "South East",
  "South West",
  "London"
)
```

```{r treemap data}
tm_df <- bind_rows(
  tribble(
    ~cause, ~cause_lab_short, ~cause_lab, ~deaths,
    "Trachea bronchus lung cancers", "Trachea, bronchus\n and lung", "Trachea, bronchus and lung cancers", 218561,
    "Breast cancer", "Breast", "Breast cancer", 177528,
    "Colon and rectum cancers", "Colorectal", "Colorectal cancer", 111364,
    "Pancreas cancer", "Pancreatic", "Pancreatic cancer", 62379,
    "Ovary cancer", "Ovarian", "Ovarian cacer", 62338,
    "Lymphomas multiple myeloma", "Lymphomas,\n multiple myeloma", "Lymphomas, multiple myeloma", 54046,
    "Oesophagus cancer", "Oesophageal", "Oesophageal cancer", 36806,
    "Leukaemia", "Leukaemia", "Leukaemia", 29465,
    "Corpus uteri cancer", "Corpus uteri", "Corpus uteri cancer", 29000,
    "Stomach cancer", "Stomach", "Stomach cancer", 26818,
    "All other cancers", "All other cancers", "All other cancers", 359262,
  ) |>
    mutate(sex = "Women"),
  tribble(
    ~cause, ~cause_lab_short, ~cause_lab, ~deaths,
    "Trachea bronchus lung cancers", "Trachea, bronchus\n and lung", "Trachea, bronchus and lung cancers", 282422,
    "Prostate cancer", "Prostate", "Prostate cancer", 164871,
    "Colon and rectum cancers", "Colorectal", "Colorectal cancer", 129382,
    "Oesophagus cancer", "Oesophageal", "Oesophageal cancer", 75457,
    "Lymphomas multiple myeloma", "Lymphomas,\n multiple myeloma", "Lymphomas, multiple myeloma", 64734,
    "Pancreas cancer", "Pancreatic", "Pancreatic cancer", 61558,
    "Bladder cancer", "Bladder", "Bladder cancer", 51883,
    "Stomach cancer", "Stomach", "Stomach cancer", 45852,
    "Leukaemia", "Leukaemia", "Leukaemia", 39368,
    "Liver cancer", "Liver", "Liver cancer", 36257,
    "All other cancers", "All other cancers", "All other cancers", 333822,
  ) |>
    mutate(sex = "Men")
) |>
  group_by(sex) |>
  mutate(prop = deaths * 100 / sum(deaths))

cause_lab_levels <- list(
  male = tm_df |>
    filter(sex == "Men") |>
    arrange(match(cause, cause_list[["male"]][-12])) |>
    pull(cause_lab) |>
    c("All cancers"),
  female = tm_df |>
    filter(sex == "Women") |>
    arrange(match(cause, cause_list[["female"]][-12])) |>
    pull(cause_lab) |>
    c("All cancers")
)
```

```{r calculate median 80q0 over time}
median_q <- lst()
for (s in c("male", "female")) {
  median_q[[s]] <- apply(
    X = cause_q[[s]],
    MARGIN = c(1, 2, 4),
    FUN = median
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(`80q0` = Freq) |>
    mutate(year = as.integer(year)) |>
    arrange()
}
```

```{r calculate median 80q0 relative change 2002-2019}
median_q_rel_change <- lst()
for (s in c("male", "female")) {
  median_q_rel_change[[s]] <- apply(
    X = (cause_q[[s]]["2019", , , ] - cause_q[[s]]["2002", , , ]) / cause_q[[s]]["2002", , , ],
    MARGIN = c(1, 3),
    FUN = median
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(d80q0 = Freq)
}
```

Relative changes:

```{r percentage relative changes}
s <- "male"
apply(
  X = (cause_q[[s]]["2019", , , ] - cause_q[[s]]["2002", , , ]) * 100 / cause_q[[s]]["2002", , , ],
  MARGIN = c(1, 3),
  FUN = quantile,
  p = c(0.025, 0.5, 0.975)
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(quantile = Var1, `rel_change` = Freq) |>
  arrange() |>
  pivot_wider(names_from = quantile, values_from = `rel_change`) |>
  filter(cause == "All cancers") |>
  arrange(-`50%`)
```

## treemap

```{r tree map}
p <- tm_df |>
  mutate(
    lab = str_c(
      cause_lab_short,
      "\n",
      format(deaths, big.mark = ","),
      "\n(",
      format(round(prop, 1), nsmall = 1),
      "%)"
    )
  ) |>
  treemap(
    index = c("sex", "lab"),
    type = "categorical",
    vSize = "deaths",
    vColor = "sex",
    palette = "Greys",
    fontsize.labels = 16,
    fontsize.title = 0,
    position.legend = "none",
    bg.labels = 0,
    align.labels = list(
      c("left", "top"),
      c("right", "bottom")
    ),
  )

quartz.save(
  here(
    "thesis_analysis",
    "cancers",
    "figures",
    "treemap.pdf"
  ),
  type = "pdf"
)
```

## maps

Maps of 80q0 in 2019 and d80q0 2002-19.
```{r map 80q0 All cancers}
for (s in c("female", "male")) {
  if (s == "female") grid_label <- "Women" else grid_label <- "Men"
  level_df <- shape |>
    left_join(
      median_q |>
        pluck(s) |>
        filter(year == 2019) |>
        filter(cause == "All cancers") |>
        mutate(LAD2020 = LAD)
    ) |>
    left_join(lookup)

  level_scale <- scale_fill_continuous_sequential(
    palette = "Reds",
    name = "Probability of dying from\nAll cancers",
    breaks = breaks_pretty(n = 3),
    limits = c(min(level_df$`80q0`) * 0.97, max(level_df$`80q0`) * 1.03)
  )

  map <- level_df |>
    ggplot(aes(fill = `80q0`)) +
    map_skeleton +
    level_scale

  london_level <- level_df |>
    filter(GOR2011 == "E12000007") |>
    ggplot(aes(fill = `80q0`)) +
    map_skeleton +
    level_scale

  p <- median_q |>
    pluck(s) |>
    filter(year == 2019) |>
    filter(cause == "All cancers") |>
    ggplot(aes(x = `80q0`, y = 1, fill = after_stat(x))) +
    ridge_skeleton +
    level_scale

  change_df <- shape |>
    left_join(
      median_q_rel_change |>
        pluck(s) |>
        filter(cause == "All cancers") |>
        mutate(LAD2020 = LAD)
    ) |>
    left_join(lookup)

  range_change <- change_df |>
    pull(d80q0) |>
    range()

  if ((range_change[1] < 0) & (range_change[2] < 0)) {
    change_mp <- range_change[2]
  } else if ((range_change[1] < 0) & (range_change[2] > 0)) {
    change_mp <- 0
  } else {
    change_mp <- range_change[1]
  }

  print(change_mp)

  change_scale <- scale_fill_continuous_divergingx(
    palette = "Geyser",
    mid = change_mp,
    name = "Change in probability for\nAll cancers",
    labels = percent,
    breaks = breaks_pretty(n = 3),
    limits = c(range_change[1] * 1.03, range_change[2] * 0.97)
  )

  map_change <- change_df |>
    ggplot(aes(fill = `d80q0`)) +
    map_skeleton +
    change_scale

  london_change <- change_df |>
    filter(GOR2011 == "E12000007") |>
    ggplot(aes(fill = `d80q0`)) +
    map_skeleton +
    change_scale

  p_change <- change_df |>
    ggplot(aes(x = `d80q0`, y = 1, fill = after_stat(x))) +
    ridge_skeleton +
    change_scale

  grid <- plot_grid(map, map_change)

  grid <- ggdraw(grid) +
    draw_plot(p, -0.1, 0.3, scale = 0.11) +
    draw_plot(p_change, 0.4, 0.3, scale = 0.11) +
    draw_plot(london_level, -0.4, -0.1, scale = 0.16) +
    draw_line(x = c(x = 0.373, 0.164), y = c(0.306, 0.38), size = 0.1) +
    draw_label("London", x = 0.094, y = 0.491, size = 3) +
    draw_plot(london_change, -0.4 + 0.5, -0.1, scale = 0.16) +
    draw_line(x = c(x = 0.373 + 0.5, 0.164 + 0.5), y = c(0.306, 0.38), size = 0.1) +
    draw_label("London", x = 0.094 + 0.5, y = 0.491, size = 3) +
    draw_label(grid_label, x = 0.1, y = 0.9, size = 6, fontface = "bold")

  save_plot(
    here(
      "thesis_analysis",
      "cancers",
      "figures",
      str_c(s, "_map_all cancers_grid", ".pdf")
    ),
    grid
  )
}
```

```{r map 80q0}
for (s in c("female", "male")) {
  for (disease in cause_list[[s]]) {
    print(disease)
    if (disease == "All cancers") {
      disease_label <- disease
    } else {
      disease_label <- tm_df |>
        filter(cause == disease) |>
        pull(cause_lab)
    }

    map <- shape |>
      left_join(
        median_q |>
          pluck(s) |>
          filter(year == 2019) |>
          filter(cause == disease) |>
          mutate(LAD2020 = LAD)
      ) |>
      ggplot(aes(fill = `80q0`)) +
      map_skeleton +
      scale_fill_continuous_sequential(
        palette = "Reds",
        name = ""
      )

    p <- median_q |>
      pluck(s) |>
      filter(year == 2019) |>
      filter(cause == disease) |>
      ggplot(aes(x = `80q0`, y = 1, fill = after_stat(x))) +
      ridge_skeleton +
      scale_fill_continuous_sequential(
        palette = "Reds",
        name = str_c("Probability of dying from\n", disease_label),
        breaks = breaks_pretty(n = 3)
      )

    range_change <- median_q_rel_change |>
      pluck(s) |>
      filter(cause == disease) |>
      pull(d80q0) |>
      range() |>
      sign() |>
      sum()

    if (range_change == 0) {
      change_mp <- 0
    } else if (range_change < 0) {
      change_mp <- median_q_rel_change |>
        pluck(s) |>
        filter(cause == disease) |>
        pull(d80q0) |>
        max()
    } else {
      change_mp <- median_q_rel_change |>
        pluck(s) |>
        filter(cause == disease) |>
        pull(d80q0) |>
        min()
    }

    map_change <- shape |>
      left_join(
        median_q_rel_change |>
          pluck(s) |>
          filter(cause == disease) |>
          mutate(LAD2020 = LAD)
      ) |>
      ggplot(aes(fill = `d80q0`)) +
      map_skeleton +
      scale_fill_continuous_divergingx(
        palette = "Geyser",
        mid = change_mp,
        name = "",
        labels = percent
      )

    p_change <- median_q_rel_change |>
      pluck(s) |>
      filter(cause == disease) |>
      ggplot(aes(x = `d80q0`, y = 1, fill = after_stat(x))) +
      ridge_skeleton +
      scale_fill_continuous_divergingx(
        palette = "Geyser",
        mid = change_mp,
        name = str_c("Change in probability for\n", disease_label),
        labels = percent,
        breaks = breaks_pretty(n = 3)
      )

    grid <- plot_grid(map, map_change)

    grid <- ggdraw(grid) +
      draw_plot(p, -0.35, -0.15, scale = 0.11) +
      draw_plot(p_change, 0.15, -0.15, scale = 0.11)

    save_plot(
      here(
        "thesis_analysis",
        "cancers",
        "figures",
        str_c(s, "_map_", str_replace_all(disease, " ", "_"), ".pdf")
      ),
      grid
    )
  }
}
```

## pair plots

Pair plot of 80q0 in 2019
```{r 80q0 correlation plot}
p_female <- median_q |>
  pluck("female") |>
  filter(year == 2019) |>
  pivot_wider(
    id_cols = c(LAD),
    names_from = cause,
    values_from = `80q0`
  ) |>
  select(all_of(cause_list[["female"]])) |>
  select(-`All cancers`) |>
  ggcorr(size = 0, label = TRUE, label_size = 2, label_round = 2) +
  geom_text(
    data = tibble(
      x = seq(cause_list[["female"]][-12]),
      y = seq(cause_list[["female"]][-12]),
      lbs = tm_df |>
        filter(sex == "Women") |>
        arrange(match(cause, cause_list[["female"]][-12])) |>
        pull(cause_lab_short)
    ),
    aes(x, y, label = str_wrap(lbs, 12)),
    nudge_x = -0.5,
    hjust = 0,
    size = 1.5
  ) +
  labs(caption = "Probability of dying in 2019, women") +
  theme_thesis() +
  pair_skeleton

p_male <- median_q |>
  pluck("male") |>
  filter(year == 2019) |>
  pivot_wider(
    id_cols = c(LAD),
    names_from = cause,
    values_from = `80q0`
  ) |>
  select(all_of(cause_list[["male"]])) |>
  select(-`All cancers`) |>
  ggcorr(size = 0, label = TRUE, label_size = 2, label_round = 2) +
  geom_text(
    data = tibble(
      x = seq(cause_list[["male"]][-12]),
      y = seq(cause_list[["male"]][-12]),
      lbs = tm_df |>
        filter(sex == "Men") |>
        arrange(match(cause, cause_list[["male"]][-12])) |>
        pull(cause_lab_short)
    ),
    aes(x, y, label = str_wrap(lbs, 12)),
    nudge_x = -0.5,
    hjust = 0,
    size = 1.5
  ) +
  labs(caption = "Probability of dying in 2019, men") +
  theme_thesis() +
  theme(legend.position = "none") +
  pair_skeleton

grid <- plot_grid(p_female + theme(legend.position = "none"), p_male)
grid <- plot_grid(get_legend(p_female), grid, ncol = 1, rel_heights = c(.1, 1))

save_plot(
  here(
    "thesis_analysis",
    "cancers",
    "figures",
    "correlation.pdf"
  ),
  grid
)
```

## poverty

```{r plot IMD}
for (s in c("female", "male")) {
  p <- median_q |>
    pluck(s) |>
    filter(year == 2019) |>
    left_join(tm_df) |>
    mutate(
      LAD2020 = LAD,
      cause_lab = replace_na(cause_lab, "All cancers")
    ) |>
    left_join(imd |> select(LAD2020, `income rank`)) |>
    left_join(lookup) |>
    ggplot(
      aes(
        x = `income rank`,
        y = `80q0`,
        colour = factor(GOR2011NM, levels = regions)
      )
    ) +
    geom_point(size = 0.1) +
    facet_wrap(
      ~ factor(cause_lab, levels = cause_lab_levels[[s]]),
      scales = "free_y",
      labeller = label_wrap_gen(20)
    ) +
    labs(
      x = "Income deprivation rank",
      y = "Probability of dying between birth and 80 years of age in 2019"
    ) +
    scale_colour_manual(values = region_pal, name = "") +
    scale_x_continuous(
      breaks = c(n_lad / 7, 6 * n_lad / 7),
      labels = c("Least deprived", "Most deprived")
    ) +
    theme_thesis() +
    theme(
      legend.key.size = unit(0.01, "npc"),
      axis.ticks.x = element_blank()
    )

  save_plot(
    here(
      "thesis_analysis",
      "cancers",
      "figures",
      str_c(s, "_IMD", ".pdf")
    ),
    p
  )
}
```

Correlation of each cancer with poverty:

```{r correlation with poverty}
median_q |>
  bind_rows(.id = "sex") |>
  filter(year == 2019) |>
  mutate(LAD2020 = LAD) |>
  left_join(imd |> select(LAD2020, `income rank`)) |>
  group_by(sex, cause) |>
  summarise(correlation = cor(`80q0`, `income rank`, method = "spearman"))
```

## distribution

```{r calculate quantiles 80q0 in 2002 and 2019}
quantile_q <- lst()
for (s in c("male", "female")) {
  quantile_q[[s]] <- apply(
    X = cause_q[[s]][c("2002", "2019"), , , ],
    MARGIN = c(1, 2, 4),
    FUN = quantile,
    p = c(0.025, 0.5, 0.975)
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(quantile = Var1, `80q0` = Freq) |>
    arrange() |>
    pivot_wider(names_from = quantile, values_from = `80q0`) |>
    group_by(year, cause) |>
    mutate(rank = rank(`50%`)) |>
    ungroup()
}
```

Range of probability of death:
```{r probability of death range}
quantile_q |>
  bind_rows(.id = "sex") |>
  mutate(LAD2020 = LAD) |>
  left_join(lookup) |>
  filter(year == 2019) |>
  filter(sex == "male") |>
  filter(cause == "All cancers") |>
  arrange(-`50%`) |>
  select(-c(LAD, LAD2020, GOR2011, cause))
```

Inequality of probability of death:
```{r inequality probability of death}
quantile_q |>
  pluck("male") |>
  mutate(LAD2020 = LAD) |>
  left_join(lookup) |>
  filter(year == 2019) |>
  group_by(cause) |>
  summarise(
    max_min = max(`50%`) / min(`50%`),
    q90_q10 = quantile(`50%`, 0.9) / quantile(`50%`, 0.1)
  )
```

```{r distribution plot}
for (s in c("female", "male")) {
  if (s == "female") {
    dist_pal <- c(desaturate(sex_pal[2], amount = 0.5), sex_pal[2])
    sex_lab <- "Women"
  } else {
    dist_pal <- c(desaturate(sex_pal[1], amount = 0.5), sex_pal[1])
    sex_lab <- "Men"
  }

  p <- quantile_q |>
    pluck(s) |>
    left_join(tm_df |> filter(sex == sex_lab)) |>
    mutate(cause_lab = replace_na(cause_lab, "All cancers")) |>
    ggplot(aes(x = rank, colour = year)) +
    geom_segment(aes(xend = rank, y = `2.5%`, yend = `97.5%`), linewidth = 0.1, alpha = 0.3) +
    geom_point(aes(y = `50%`), size = 0.3, stroke = 0.1, shape = 16) +
    facet_wrap(
      ~ factor(cause_lab, levels = cause_lab_levels[[s]]),
      scales = "free",
      labeller = label_wrap_gen(20)
    ) +
    labs(
      x = "Ranking of probability of dying",
      y = "Probability of dying between birth and 80 years of age"
    ) +
    scale_colour_manual(
      values = dist_pal,
      name = ""
    ) +
    guides(colour = guide_legend(override.aes = list(size = 1, linewidth = 0.5))) +
    theme_thesis() +
    theme(
      legend.position = "top",
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
    )

  save_plot(
    here(
      "thesis_analysis",
      "cancers",
      "figures",
      str_c(s, "_distribution", ".pdf")
    ),
    p
  )
}
```

## Change quantile

```{r calculate quantiles d80q0}
quantile_q_change <- lst()
for (s in c("male", "female")) {
  quantile_q_change[[s]] <- apply(
    X = (cause_q[[s]]["2019", , , ] - cause_q[[s]]["2002", , , ]) / cause_q[[s]]["2002", , , ],
    MARGIN = c(1, 3),
    FUN = quantile,
    p = c(0.025, 0.5, 0.975)
  ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(quantile = Var1, `80q0` = Freq) |>
    arrange() |>
    pivot_wider(names_from = quantile, values_from = `80q0`) |>
    group_by(cause) |>
    mutate(rank = rank(`50%`)) |>
    ungroup()
}
```

```{r change plot}
for (s in c("female", "male")) {
  if (s == "female") {
    sex_lab <- "Women"
  } else {
    sex_lab <- "Men"
  }

  p <- quantile_q_change |>
    pluck(s) |>
    left_join(tm_df |> filter(sex == sex_lab)) |>
    mutate(
      LAD2020 = LAD,
      cause_lab = replace_na(cause_lab, "All cancers")
    ) |>
    left_join(lookup) |>
    mutate(
      region = factor(GOR2011NM, levels = regions)
    ) |>
    group_by(cause) |>
    mutate(
      rank_ = rank(as.numeric(region) * n_lad + rank)
    ) |>
    ggplot(aes(x = rank_, colour = region)) +
    geom_segment(aes(xend = rank_, y = `2.5%`, yend = `97.5%`), linewidth = 0.1, alpha = 0.3) +
    geom_point(aes(y = `50%`), size = 0.3, stroke = 0.1, shape = 16) +
    facet_wrap(
      ~ factor(cause_lab, levels = cause_lab_levels[[s]]),
      scales = "free",
      labeller = label_wrap_gen(20)
    ) +
    labs(
      x = "",
      y = "Percent change in probability of dying from 2002 to 2019"
    ) +
    scale_colour_manual(values = region_pal, name = "") +
    scale_y_continuous(labels = percent) +
    guides(colour = guide_legend(override.aes = list(size = 1, linewidth = 0.5))) +
    theme_thesis() +
    theme(
      legend.key.size = unit(0.01, "npc"),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
    )

  save_plot(
    here(
      "thesis_analysis",
      "cancers",
      "figures",
      str_c(s, "_change_distribution", ".pdf")
    ),
    p
  )
}
```
