---
title: "eda"
author: "Theo Rashid"
date: "07/03/2023"
format: html
---

## cause rates

```{r imports}
library(here)
library(tidyverse)
library(cowplot)
library(colorspace)
library(scales)
library(geojsonsf)
library(sf)
library(ggridges)
library(ggrepel)

source(here("thesis_analysis", "theme_thesis.R"))
source(here("thesis_analysis", "palette_thesis.R"))
source(here("thesis_analysis", "skeletons.R"))
```

## data

```{r data}
shape <- geojson_sf(here("data", "covariates", "LAD2020_ENG_BGC.geojson"))

lookup <- read_csv(
  here(
    "data",
    "covariates",
    "LSOA_MSOA_LAD_GOR_CTRY_lookup.csv"
  )
) |>
  select(LAD2020, LAD2020NM, GOR2011, GOR2011NM) |>
  distinct() |>
  arrange(LAD2020)

n_lad <- length(unique(lookup$LAD2020NM))
```

## map of district-level life expectancy

Maps of life expectancy from all deaths 2002-19.
```{r map e0}
e0_LAD <- read_csv(here("data", "eda", "e0_eng_LAD.csv"))

level_df_female <- shape |>
  left_join(e0_LAD |>
    filter(sex == 2)) |>
  left_join(lookup)

level_df_male <- shape |>
  left_join(e0_LAD |>
    filter(sex == 1)) |>
  left_join(lookup)

level_scale_female <- scale_fill_continuous_sequential(
  palette = "Reds",
  rev = FALSE,
  name = str_c("Life expectancy, women"),
  breaks = breaks_pretty(n = 5),
  limits = c(min(level_df_female$`ex`) * 0.97, max(level_df_female$`ex`) * 1.03),
  l1 = 0,
  p1 = 2,
  p2 = 3
)

level_scale_male <- scale_fill_continuous_sequential(
  palette = "Reds",
  rev = FALSE,
  name = str_c("Life expectancy, men"),
  breaks = breaks_pretty(n = 5),
  limits = c(min(level_df_male$ex) * 0.97, max(level_df_male$ex) * 1.03),
  l1 = 0,
  p1 = 2,
  p2 = 3
)

london_female <- level_df_female |>
  filter(GOR2011 == "E12000007") |>
  ggplot(aes(fill = ex)) +
  map_skeleton +
  level_scale_female

london_male <- level_df_male |>
  filter(GOR2011 == "E12000007") |>
  ggplot(aes(fill = ex)) +
  map_skeleton +
  level_scale_male

p_female <- e0_LAD |>
  filter(sex == 2) |>
  ggplot(aes(x = `ex`, y = 1, fill = after_stat(x))) +
  ridge_skeleton +
  level_scale_female

p_male <- e0_LAD |>
  filter(sex == 1) |>
  ggplot(aes(x = `ex`, y = 1, fill = after_stat(x))) +
  ridge_skeleton +
  level_scale_male

grid <- plot_grid(
  level_df_female |>
    ggplot(aes(fill = `ex`)) +
    map_skeleton +
    level_scale_female,
  level_df_male |>
    ggplot(aes(fill = `ex`)) +
    map_skeleton +
    level_scale_male
)

grid <- ggdraw(grid) +
  draw_plot(p_female, -0.1, 0.35, scale = 0.11) +
  draw_plot(p_male, 0.4, 0.35, scale = 0.11) +
  draw_plot(london_female, -0.4, -0.1, scale = 0.16) +
  draw_line(x = c(x = 0.373, 0.164), y = c(0.306, 0.38), size = 0.1) +
  draw_label("London", x = 0.094, y = 0.491, size = 3) +
  draw_plot(london_male, -0.4 + 0.5, -0.1, scale = 0.16) +
  draw_line(x = c(x = 0.373 + 0.5, 0.164 + 0.5), y = c(0.306, 0.38), size = 0.1) +
  draw_label("London", x = 0.094 + 0.5, y = 0.491, size = 3)

save_plot(
  here(
    "thesis_analysis",
    "eda",
    "figures",
    str_c("e0_map_LAD_2002_2019.pdf")
  ),
  grid
)
```

## age-specific death rates

Age-specific death rates for England 2002-19
```{r age-mx plot}
mx <- read_csv(here("data", "eda", "deaths_eng_age_time.csv")) |>
  mutate(sex = recode(sex, `1` = "men", `2` = "women"))

p <- mx |>
  group_by(sex, age_group) |>
  summarise(death_rate = sum(deaths) / sum(population)) |>
  mutate(label = ifelse(age_group == max(age_group), sex, NA_character_)) |>
  ggplot(aes(x = age_group, y = death_rate, group = sex, colour = sex)) +
  geom_line(linewidth = 0.8) +
  geom_label_repel(
    aes(x = age_group, label = label),
    nudge_x = 10,
    nudge_y = 0.1,
    na.rm = TRUE,
    size = 4
  ) +
  scale_colour_manual(values = sex_pal) +
  scale_x_continuous(expand = c(0, NA), breaks = c(c(0, 1), seq(5, 85, 5))) +
  scale_y_continuous(trans = "log10") +
  labs(x = "Age group", y = "Death rate") +
  theme_thesis() +
  theme(legend.position = "none")

save_plot(
  here(
    "thesis_analysis",
    "eda",
    "figures",
    "age_mx.pdf"
  ),
  p
)
```

```{r age-mx plot void}
p <- mx |>
  group_by(sex, age_group) |>
  summarise(death_rate = sum(deaths) / sum(population)) |>
  ggplot(aes(x = age_group, y = death_rate, group = sex, colour = sex)) +
  geom_line(linewidth = 0.8) +
  scale_colour_manual(values = sex_pal) +
  scale_y_continuous(trans = "log10") +
  theme_void() +
  theme(legend.position = "none")

save_plot(
  here(
    "thesis_analysis",
    "eda",
    "figures",
    "age_mx_void.pdf"
  ),
  p
)
```

## age-specific death rates and life expectancy over time

Age-specific death rates for England 2002-19
```{r age-mx over time plot}
mx <- read_csv(here("data", "eda", "deaths_eng_age_time.csv")) |>
  mutate(sex = recode(sex, `1` = "men", `2` = "women"))

e0 <- read_csv(here("data", "eda", "e0_eng_time.csv")) |>
  mutate(sex = recode(sex, `1` = "men", `2` = "women"))

p <- mx |>
  mutate(
    broad_age_group = case_when(
      age_group < 15 ~ "0-14 years, adolescence",
      age_group >= 15 & age_group < 30 ~ "15-29 years, young adulthood",
      age_group >= 30 & age_group < 70 ~ "30-69 years, working ages",
      age_group >= 70 ~ "70+ years, older ages",
    )
  ) |>
  group_by(sex, YEAR, broad_age_group) |>
  summarise(death_rate = sum(deaths) / sum(population)) |>
  ggplot(aes(x = YEAR, y = death_rate, group = sex, colour = sex)) +
  geom_line(linewidth = 0.8) +
  facet_wrap(~broad_age_group, scales = "free_y", ncol = 1) +
  scale_colour_manual(values = sex_pal) +
  scale_x_continuous(breaks = breaks_pretty(8)) +
  scale_y_continuous(trans = "log10") +
  labs(x = "year", y = "Death rate") +
  theme_thesis() +
  theme(legend.position = "none")

p_e0 <- e0 |>
  mutate(label = ifelse(YEAR == max(YEAR), sex, NA_character_)) |>
  ggplot(aes(x = YEAR, y = ex, group = sex, colour = sex)) +
  geom_line(linewidth = 0.8) +
  geom_label_repel(
    aes(x = YEAR, label = label),
    nudge_x = 0,
    nudge_y = 0.1,
    na.rm = TRUE,
    size = 3
  ) +
  scale_colour_manual(values = sex_pal) +
  scale_x_continuous(breaks = breaks_pretty(8)) +
  labs(x = "year", y = "Life expectancy") +
  theme_thesis() +
  theme(legend.position = "none")

save_plot(
  here(
    "thesis_analysis",
    "eda",
    "figures",
    "age_mx_time.pdf"
  ),
  plot_grid(p, p_e0, ncol = 2, rel_widths = c(1, 1))
)
```

## simulated death rates

```{r simulated}
set.seed(1)
simulated <- read_csv(here("data", "eda", "deaths_eng_age_time.csv")) |>
  filter(sex == 1) |>
  filter(age_group == 1 | age_group == 80) |>
  mutate(
    simulated = rpois(death_rate, lambda = death_rate * 1000),
    expected = death_rate * 1000,
    age_group_lab = case_when(
      age_group == 1 ~ "1-4 years",
      age_group == 80 ~ "80-84 years"
    )
  ) |>
  pivot_longer(cols = c(simulated, expected), names_to = "death_type", values_to = "deaths_sim")

p <- simulated |>
  ggplot(aes(x = YEAR, y = deaths_sim, group = death_type, linetype = death_type)) +
  geom_line(linewidth = 0.3) +
  geom_point(size = 0.6) +
  facet_wrap(~age_group_lab, scales = "free_y", ncol = 1) +
  scale_linetype_manual(values = c("dotted", "solid")) +
  scale_x_continuous(breaks = breaks_pretty(8)) +
  labs(x = "year", y = "Deaths") +
  theme_thesis() +
  theme(legend.position = "top", legend.title = element_blank())

save_plot(
  here(
    "thesis_analysis",
    "eda",
    "figures",
    "age_mx_time_sim.pdf"
  ),
  p
)
```
