---
title: "england"
author: "Theo Rashid"
date: "16/01/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## cause rates

```{r imports}
library(here)
library(tidyverse)
library(abind)
library(cowplot)
library(colorspace)
library(scales)
library(geojsonsf)
library(sf)
library(ggridges)

source(here("thesis_analysis", "theme_thesis.R"))
source(here("thesis_analysis", "palette_thesis.R"))
source(here("thesis_analysis", "skeletons.R"))
```

## data

```{r data}
args <- lst(region = "MSOA", model = "nb_nested_as_at_st")

sexes <- c("women", "men")

e0 <- abind(
  read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_female_",
        args$model,
        "_e0.rds"
      )
    )
  ),
  read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_male_",
        args$model,
        "_e0.rds"
      )
    )
  ),
  along = 0,
  new.names = sexes
)

dimnames(e0) <- list(
  sex = dimnames(e0)[[1]],
  year = dimnames(e0)[[2]],
  MSOA2011 = dimnames(e0)[[3]],
  sample = dimnames(e0)[[4]]
)

e0_global <- abind(
  read_rds(
    here(
      "data",
      "life_table",
      str_c(args$region, "_GLOBAL_female_nested_as_at_e0.rds")
    )
  ),
  read_rds(
    here(
      "data",
      "life_table",
      str_c(args$region, "_GLOBAL_male_nested_as_at_e0.rds")
    )
  ),
  along = 0,
  new.names = sexes
) |>
  apply(
    MARGIN = c(1, 2),
    FUN = median
  ) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(`e0` = Freq, sex = Var1, year = Var2) |>
  mutate(year = as.integer(year)) |>
  arrange()

median_q <- bind_rows(
  read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_female_",
        args$model,
        "_q_agg.rds"
      )
    )
  ) |>
    mutate(sex = "women"),
  read_rds(
    here(
      "data",
      "life_table",
      str_c(
        args$region,
        "_male_",
        args$model,
        "_q_agg.rds"
      )
    )
  ) |>
    mutate(sex = "men")
) |>
  mutate(
    age_group = factor(
      age_group,
      levels = c("15q0", "15q15", "40q30", "10q70")
    ),
    year = YEAR
  ) |>
  mutate(
    age_range = recode(
      age_group,
      "15q0"  = "Childhood and early\nadolescence (0-14)",
      "15q15" = "Young adulthood\n(15-29)",
      "40q30" = "Working ages (30-69)",
      "10q70" = "Older ages (70-79)"
    )
  ) |>
  select(sex, MSOA2011, year, age_group, age_range, qmed)
```

```{r covariate and shape data}
imd <- bind_rows(
  read_csv(here("data", "covariates", "IMD_MSOA2011_2004.csv")) |> mutate(year = 2002),
  read_csv(here("data", "covariates", "IMD_MSOA2011_2019.csv")) |> mutate(year = 2019)
) |>
  group_by(year) |>
  mutate(
    `Poverty` = rank(`income score`),
    `Unemployment` = rank(`employment score`),
    `Education` = rank(`education, skills and training score`)
  ) |>
  select(MSOA2011, year, Poverty, Unemployment, Education)

lookup <- read_csv(
  here(
    "data",
    "covariates",
    "LSOA_MSOA_LAD_GOR_CTRY_lookup.csv"
  )
) |>
  select(MSOA2011, LAD2020, LAD2020NM, GOR2011, GOR2011NM) |>
  distinct() |>
  arrange(MSOA2011)

n_msoa <- length(unique(lookup$MSOA2011))

shape <- geojson_sf(here("data", "covariates", "MSOA2011_EW_BGC.geojson")) |>
  filter(MSOA2011 %in% (lookup |> pull(MSOA2011)))
```

```{r calculate median e0 in over time}
median_e0 <- apply(
  X = e0,
  MARGIN = c(1, 2, 3),
  FUN = median
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(`e0` = Freq) |>
  mutate(year = as.integer(year)) |>
  arrange()
```

```{r calculate median e0 change 2002-2019}
median_e0_change <- apply(
  X = e0[, "2019", , ] - e0[, "2002", , ],
  MARGIN = c(1, 2),
  FUN = median
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(de0 = Freq)
```

## distribution

```{r calculate quantiles e0 in 2002 and 2019}
quantile_e0 <- apply(
  X = e0[, c("2002", "2019"), , ],
  MARGIN = c(1, 2, 3),
  FUN = quantile,
  p = c(0.025, 0.5, 0.975)
) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(quantile = Var1, `e0` = Freq) |>
  arrange() |>
  pivot_wider(names_from = quantile, values_from = `e0`) |>
  group_by(sex, year) |>
  mutate(rank = rank(`50%`)) |>
  ungroup()
```

```{r calculate rank of benchmark countries}
n_ctry <- 5
benchmark <- tibble(
  sex = c(rep("women", n_ctry), rep("men", n_ctry)),
  country = c(
    c("England", "USA", "Hong Kong", "Spain", "Bulgaria"),
    c("England", "USA", "Hong Kong", "Switzerland", "Latvia")
  ),
  year = rep("2019", n_ctry * 2),
  e0_global = c(
    c(83.7, 81.4, 88.1, 86.2, 78.5), # Female 2019
    c(80.1, 76.3, 82.2, 81.9, 70.8) # Male 2019
  )
) |>
  mutate(
    label = str_c(country, " ", "(", e0_global, ")"),
    arrow_start = e0_global + c(c(4, 4, 5, 4, 4), c(4, 4, 5, 4, 5.5)),
    arrow_end = e0_global + c(rep(2, n_ctry * 2))
  ) |>
  mutate(text_y = arrow_start + 0.5)

for (i in seq_along(benchmark$sex)) {
  global <- benchmark[i, ] |> pull("e0_global")
  benchmark[i, "rank"] <- quantile_e0 |>
    filter(sex == benchmark[i, ] |> pull(sex)) |>
    filter(year == 2019) |>
    mutate(min_rank = rank(abs(`50%` - global))) |>
    filter(min_rank == 1) |>
    pull("rank")
}
```

```{r distribution plot}
p <- quantile_e0 |>
  mutate(
    sex_year = factor(
      str_c(sex, ", ", year),
      levels = str_c(rep(sexes, each = 2), ", ", rep(c(2002, 2019), 2))
    )
  ) |>
  ggplot(aes(x = rank)) +
  geom_segment(
    aes(
      xend = rank,
      y = `2.5%`,
      yend = `97.5%`,
      colour = sex_year
    ),
    alpha = 0.05,
    linewidth = 0.1
  ) +
  geom_point(aes(y = `50%`, colour = sex_year), size = 0.1) +
  facet_wrap(~ factor(sex, levels = sexes)) +
  scale_colour_manual(
    values = c(
      desaturate(sex_pal[2], amount = 0.5), sex_pal[2],
      desaturate(sex_pal[1], amount = 0.5), sex_pal[1]
    ),
    name = ""
  ) +
  scale_x_continuous(
    breaks = c(n_msoa / 7, n_msoa * 6 / 7),
    labels = c("Lowest life expectancy", "Highest life expectancy")
  ) +
  guides(colour = guide_legend(override.aes = list(size = 1, linewidth = 1))) +
  labs(x = "Life expectancy rank", y = "Life expectancy (years)") +
  theme_thesis() +
  theme(
    legend.position = "top",
    axis.ticks.x = element_blank(),
    strip.text = element_blank()
  )

p <- p +
  geom_point(data = benchmark, aes(x = rank, y = e0_global), size = 0.4) +
  geom_segment(
    data = benchmark,
    aes(
      x = rank, xend = rank,
      y = arrow_start, yend = arrow_end
    ),
    size = 0.1,
    alpha = 0.6,
    arrow = arrow(angle = 20, type = "closed", length = unit(3, units = "pt"))
  ) +
  geom_text(
    data = benchmark,
    aes(x = rank, y = text_y, label = label),
    size = 1.5
  ) +
  coord_cartesian(clip = "off")

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "distribution.pdf"
  ),
  p
)
```

## time series

```{r time series plot}
p <- median_e0 |>
  mutate(sex = factor(sex, levels = sexes)) |>
  ggplot(aes(x = year, y = e0, colour = sex)) +
  geom_jitter(
    width = 0.05,
    size = 0.01,
    alpha = 0.1
  ) +
  geom_line(data = e0_global, linewidth = 0.8) +
  facet_wrap(~ factor(sex, levels = sexes)) +
  scale_colour_manual(values = rev(sex_pal), name = "") +
  scale_x_continuous(breaks = breaks_pretty(8)) +
  labs(x = "year", y = "Life expectancy (years)") +
  theme_thesis() +
  theme(
    legend.position = "top",
    strip.text = element_blank()
  )

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "scatter_time.pdf"
  ),
  p
)
```

```{r inequality time series plot}
p <- left_join(
  apply(
    X = e0,
    MARGIN = c(1, 2, 4),
    FUN = \(x) max(x) - min(x)
  ) |>
    apply(
      MARGIN = c(1, 2),
      FUN = median
    ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(`max_min` = Freq),
  apply(
    X = e0,
    MARGIN = c(1, 2, 4),
    FUN = \(x) quantile(x, 0.99) - quantile(x, 0.01)
  ) |>
    apply(
      MARGIN = c(1, 2),
      FUN = median
    ) |>
    as.data.frame.table(stringsAsFactors = FALSE) |>
    as_tibble() |>
    rename(`99_1` = Freq)
) |>
  mutate(year = as.integer(year)) |>
  pivot_longer(
    cols = c(max_min, `99_1`),
    names_to = "range_type",
    values_to = "ranges"
  ) |>
  mutate(sex = factor(sex, levels = sexes)) |>
  ggplot(aes(x = year, y = ranges, colour = sex)) +
  geom_point(size = 0.8, alpha = 0.8) +
  geom_line(
    aes(linetype = range_type),
    linewidth = 0.5,
    alpha = 0.8
  ) +
  facet_wrap(~sex) +
  scale_x_continuous(breaks = pretty_breaks(8)) +
  scale_colour_manual(values = rev(sex_pal), name = "") +
  scale_linetype(
    labels = c(
      expression(paste(99^
        {
          th
        } - 1^{
          st
        }, " percentile difference")),
      "maximum-minimum difference"
    ),
    name = ""
  ) +
  guides(linetype = guide_legend(ncol = 1), colour = guide_legend(ncol = 1)) +
  labs(
    x = "year",
    y = "Life expectancy difference (years)"
  ) +
  theme_thesis() +
  theme(
    legend.position = "top",
    strip.text = element_blank()
  )

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "inequality_time.pdf"
  ),
  p
)
```

## maps

```{r map level 2019 1}
scale_sex <- list(
  women = scale_fill_continuous_divergingx(
    palette = "RdBu",
    mid = e0_global |>
      filter(sex == "women") |>
      filter(year == 2019) |>
      pull(e0),
    p1 = 0.8,
    p2 = 0.8,
    p3 = 0.8,
    p4 = 0.8,
    name = str_c("Life expectancy, women"),
    breaks = breaks_pretty(n = 5)
  ),
  men = scale_fill_continuous_divergingx(
    palette = "RdBu",
    mid = e0_global |>
      filter(sex == "men") |>
      filter(year == 2019) |>
      pull(e0),
    p1 = 0.8,
    p2 = 0.8,
    p3 = 0.8,
    p4 = 0.8,
    name = str_c("Life expectancy, men"),
    breaks = breaks_pretty(n = 5)
  )
)

maps <- list()
manchester <- list()
liverpool <- list()
birmingham <- list()
leeds <- list()
london <- list()
ridges <- list()

for (s in sexes) {
  plot_df <- shape |>
    left_join(lookup) |>
    left_join(
      median_e0 |>
        filter(sex == s) |>
        filter(year == 2019)
    )

  maps[[s]] <- plot_df |>
    ggplot(aes(fill = `e0`)) +
    map_skeleton_msoa +
    scale_sex[[s]]

  manchester[[s]] <- plot_df |>
    filter(LAD2020 == "E08000003") |>
    ggplot(aes(fill = `e0`)) +
    map_skeleton_msoa +
    scale_sex[[s]]

  liverpool[[s]] <- plot_df |>
    filter(LAD2020 == "E08000012") |>
    ggplot(aes(fill = `e0`)) +
    map_skeleton_msoa +
    scale_sex[[s]]

  birmingham[[s]] <- plot_df |>
    filter(LAD2020 == "E08000025") |>
    ggplot(aes(fill = `e0`)) +
    map_skeleton_msoa +
    scale_sex[[s]]

  leeds[[s]] <- plot_df |>
    filter(LAD2020 == "E08000035") |>
    ggplot(aes(fill = `e0`)) +
    map_skeleton_msoa +
    scale_sex[[s]]

  london[[s]] <- plot_df |>
    filter(GOR2011 == "E12000007") |>
    ggplot(aes(fill = `e0`)) +
    map_skeleton_msoa +
    scale_sex[[s]]

  ridges[[s]] <- median_e0 |>
    filter(sex == s) |>
    filter(year == 2019) |>
    ggplot(aes(x = e0, y = 1, fill = after_stat(x))) +
    ridge_skeleton +
    scale_sex[[s]]
}
```

```{r map level 2019 2}
grid <- plot_grid(maps[["women"]], maps[["men"]])

grid <- ggdraw(grid) +
  draw_plot(ridges[["women"]], -0.1, 0.3, scale = 0.11) +
  draw_plot(ridges[["men"]], 0.4, 0.3, scale = 0.11)

grid <- ggdraw(grid) +
  draw_plot(manchester[["women"]], -0.35, 0.38, scale = 0.1) +
  draw_line(x = c(x = 0.255, 0.149), y = c(0.597, 0.83), size = 0.1) +
  draw_label("Manchester", x = 0.15, y = 0.94, size = 3) +
  draw_plot(liverpool[["women"]], -0.37, 0.23, scale = 0.1) +
  draw_line(x = c(x = 0.215, 0.154), y = c(0.587, 0.73), size = 0.1) +
  draw_label("Liverpool", x = 0.127, y = 0.79, size = 3) +
  draw_plot(birmingham[["women"]], -0.39, 0.1, scale = 0.1) +
  draw_line(x = c(x = 0.273, 0.135), y = c(0.449, 0.568), size = 0.1) +
  draw_label("Birmingham", x = 0.11, y = 0.658, size = 3) +
  draw_plot(leeds[["women"]], -0.05, 0.14, scale = 0.1) +
  draw_line(x = c(x = 0.294, 0.413), y = c(0.64, 0.632), size = 0.1) +
  draw_label("Leeds", x = 0.438, y = 0.694, hjust = 0, vjust = 0, size = 3) +
  draw_plot(london[["women"]], -0.4, -0.1, scale = 0.16) +
  draw_line(x = c(x = 0.373, 0.164), y = c(0.306, 0.38), size = 0.1) +
  draw_label("London", x = 0.094, y = 0.491, size = 3)
```

```{r map level 2019 3}
grid <- ggdraw(grid) +
  draw_plot(manchester[["men"]], -0.35 + 0.5, 0.38, scale = 0.1) +
  draw_line(x = c(x = 0.255 + 0.5, 0.149 + 0.5), y = c(0.597, 0.83), size = 0.1) +
  draw_label("Manchester", x = 0.15 + 0.5, y = 0.94, size = 3) +
  draw_plot(liverpool[["men"]], -0.37 + 0.5, 0.23, scale = 0.1) +
  draw_line(x = c(x = 0.215 + 0.5, 0.154 + 0.5), y = c(0.587, 0.73), size = 0.1) +
  draw_label("Liverpool", x = 0.127 + 0.5, y = 0.79, size = 3) +
  draw_plot(birmingham[["men"]], -0.39 + 0.5, 0.1, scale = 0.1) +
  draw_line(x = c(x = 0.273 + 0.5, 0.135 + 0.5), y = c(0.449, 0.568), size = 0.1) +
  draw_label("Birmingham", x = 0.11 + 0.5, y = 0.658, size = 3) +
  draw_plot(leeds[["men"]], -0.05 + 0.5, 0.14, scale = 0.1) +
  draw_line(x = c(x = 0.294 + 0.5, 0.413 + 0.5), y = c(0.64, 0.632), size = 0.1) +
  draw_label("Leeds", x = 0.45 + 0.5, y = 0.697, size = 3) +
  draw_plot(london[["men"]], -0.4 + 0.5, -0.1, scale = 0.16) +
  draw_line(x = c(x = 0.373 + 0.5, 0.164 + 0.5), y = c(0.306, 0.38), size = 0.1) +
  draw_label("London", x = 0.094 + 0.5, y = 0.491, size = 3)

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "map_level.pdf"
  ),
  grid
)
```

```{r map level 2019 hex carto}
shape_carto <- geojson_sf(here("data", "covariates", "MSOA_hex.geojson")) |>
  mutate(MSOA2011 = msoa11cd) |>
  filter(MSOA2011 %in% (lookup |> pull(MSOA2011)))

carto_background <- geojson_sf(here("data", "covariates", "MSOA_hex_background.geojson"))
carto_labels <- geojson_sf(here("data", "covariates", "MSOA_hex_group_labels.geojson")) |>
  filter(RegionNation != "Wales") |>
  mutate(
    lon = st_coordinates(geometry)[, 1],
    lat = st_coordinates(geometry)[, 2]
  )

maps <- list()
ridges <- list()
for (s in sexes) {
  maps[[s]] <- shape_carto |>
    left_join(
      median_e0 |>
        filter(sex == s) |>
        filter(year == 2019)
    ) |>
    ggplot(aes(fill = `e0`)) +
    geom_sf(
      fill = "grey95",
      colour = "grey70",
      linewidth = 0.1,
      data = carto_background
    ) +
    map_skeleton +
    scale_sex[[s]] +
    geom_label(
      aes(label = `Group-labe`, x = lon, y = lat),
      size = 1,
      label.size = 0,
      fill = NA,
      data = carto_labels
    )

  ridges[[s]] <- median_e0 |>
    filter(sex == s) |>
    filter(year == 2019) |>
    ggplot(aes(x = e0, y = 1, fill = after_stat(x))) +
    ridge_skeleton +
    scale_sex[[s]]
}

grid <- plot_grid(maps[["women"]], maps[["men"]])

grid <- ggdraw(grid) +
  draw_plot(ridges[["women"]], -0.1, 0.3, scale = 0.11) +
  draw_plot(ridges[["men"]], 0.4, 0.3, scale = 0.11)

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "map_hex_carto.pdf"
  ),
  grid
)
```

## sex comparison

```{r inequality time series plot}
p_level <- median_e0 |>
  filter(year == 2019) |>
  pivot_wider(names_from = sex, values_from = `e0`) |>
  ggplot(aes(x = women, y = men)) +
  geom_abline(slope = 1, intercept = 0, colour = "grey20", linewidth = 0.5) +
  geom_point(colour = "#5b6980f5", size = 0.1, alpha = 0.5) +
  scale_x_continuous(limits = median_e0 |> filter(year == 2019) |> pull(e0) |> range()) +
  scale_y_continuous(limits = median_e0 |> filter(year == 2019) |> pull(e0) |> range()) +
  labs(
    x = "Life expectancy in 2019, women",
    y = "Life expectancy in 2019, men"
  ) +
  theme_thesis()

p_change <- median_e0_change |>
  pivot_wider(names_from = sex, values_from = `de0`) |>
  ggplot(aes(x = women, y = men)) +
  geom_abline(slope = 1, intercept = 0, colour = "grey20", linewidth = 0.5) +
  geom_point(colour = "#5b6980f5", size = 0.1, alpha = 0.5) +
  scale_x_continuous(limits = median_e0_change |> pull(de0) |> range()) +
  scale_y_continuous(limits = median_e0_change |> pull(de0) |> range()) +
  labs(
    x = "Life expectancy change from 2002 to 2019, women",
    y = "Life expectancy change from 2002 to 2019, men"
  ) +
  theme_thesis()

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "sex_comp.pdf"
  ),
  plot_grid(p_level + coord_equal(), p_change + coord_equal())
)
```

## jitter change between periods

```{r calculate change 2002, 2006, 2010, 2014, 2019}
median_e0_changes <- apply(
  X = e0[, c("2002", "2006", "2010", "2014", "2019"), , ],
  MARGIN = c(1, 3, 4),
  FUN = diff
) |>
  apply(
    MARGIN = c(1, 2, 3),
    FUN = median
  ) |>
  as.data.frame.table(stringsAsFactors = FALSE) |>
  as_tibble() |>
  rename(de0 = Freq) |>
  mutate(
    period = recode(
      year,
      `2006` = "2002-2006",
      `2010` = "2006-2010",
      `2014` = "2010-2014",
      `2019` = "2014-2019"
    )
  ) |>
  left_join(
    median_e0 |>
      filter(year == 2002 | year == 2006 | year == 2010 | year == 2014) |>
      group_by(sex, year) |>
      mutate(percentile = ntile(e0, 100) / 100) |>
      ungroup() |>
      mutate(
        period = recode(
          year,
          `2002` = "2002-2006",
          `2006` = "2006-2010",
          `2010` = "2010-2014",
          `2014` = "2014-2019"
        )
      ) |>
      select(-e0, -year)
  )
```

```{r e0 jitter change plot}
p <- ggplot(
  data = median_e0_changes |>
    group_by(sex, period) |>
    summarise(
      pct1  = quantile(de0, p = 0.01),
      pct5  = quantile(de0, p = 0.05),
      pct25 = quantile(de0, p = 0.25),
      pct50 = quantile(de0, p = 0.50),
      pct75 = quantile(de0, p = 0.75),
      pct95 = quantile(de0, p = 0.95),
      pct99 = quantile(de0, p = 0.99)
    ),
  aes(x = period)
) +
  geom_hline(yintercept = 0, linewidth = 0.05, alpha = 0.5) +
  geom_crossbar(
    aes(ymin = pct25, y = pct50, ymax = pct75),
    linewidth = 0.2,
    width = 0.3,
    colour = "grey25"
  ) +
  geom_errorbar(
    aes(ymin = pct5, ymax = pct95),
    linewidth = 0.2,
    width = 0.2,
    colour = "grey25"
  ) +
  geom_errorbar(
    aes(ymin = pct1, ymax = pct99),
    linewidth = 0.2,
    width = 0.1,
    colour = "grey25"
  ) +
  geom_jitter(
    data = median_e0_changes,
    aes(x = period, y = de0, colour = percentile),
    size = 0.01,
    alpha = 0.1,
    width = 0.4
  ) +
  facet_wrap(~ factor(sex, levels = sexes)) +
  scale_colour_continuous_divergingx(
    palette = "Zissou",
    name = "Percentile of life expectancy at the start of each time period",
    mid = 0.5,
    rev = TRUE,
    limits = c(0, 1),
    labels = percent
  ) +
  labs(
    x = "Time period",
    y = "Life expectancy change during period (years)"
  ) +
  theme_thesis() +
  theme(
    axis.ticks.x = element_blank(),
    axis.line = element_blank(),
    panel.border = element_blank(),
    legend.direction = "horizontal",
    legend.position = "bottom",
    legend.key.width = unit(30, units = "pt"),
    legend.key.height = unit(5, units = "pt"),
    legend.title = element_text(
      size = 5,
      face = "bold"
    )
  ) +
  guides(
    colour = guide_colourbar(
      title.position = "top",
      title.hjust = 0
    )
  )

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "change.pdf"
  ),
  p
)
```

# q jitter

```{r q jitter plot}
p <- median_q |>
  filter(year == 2002 | year == 2019) |>
  mutate(
    sex_year = factor(
      str_c(sex, ", ", year),
      levels = str_c(rep(sexes, each = 2), ", ", rep(c(2002, 2019), 2))
    )
  ) |>
  ggplot(aes(x = age_range, y = qmed, colour = sex_year)) +
  geom_jitter(
    position = position_jitterdodge(jitter.width = 0.5, dodge.width = 0.8),
    size = 0.01,
    alpha = 0.1
  ) +
  facet_wrap(~ factor(sex, levels = sexes)) +
  scale_colour_manual(
    values = c(
      desaturate(sex_pal[2], amount = 0.5), sex_pal[2],
      desaturate(sex_pal[1], amount = 0.5), sex_pal[1]
    ),
    name = ""
  ) +
  scale_y_continuous(
    trans = "log10",
    breaks = c(0.001, 0.005, 0.01, 0.05, 0.1, 0.5),
    labels = percent
  ) +
  guides(colour = guide_legend(override.aes = list(size = 1, alpha = 0.8))) +
  labs(
    x = "Time period",
    y = "Life expectancy change during period (years)"
  ) +
  theme_thesis() +
  theme(
    legend.position = "top",
    axis.ticks.x = element_blank(),
    strip.text = element_blank()
  )

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "q_change.pdf"
  ),
  p
)
```

## poverty

```{r plot IMD}
p <- median_e0 |>
  filter(year == 2002 | year == 2019) |>
  pivot_wider(
    names_from = year,
    values_from = e0,
    names_prefix = "e0_"
  ) |>
  left_join(
    imd |>
      pivot_longer(
        cols = c(Poverty, Unemployment, Education),
        names_to = "IMD",
        values_to = "rank"
      ) |>
      pivot_wider(
        names_from = year,
        values_from = rank,
        names_prefix = "rank_"
      )
  ) |>
  mutate(sex = factor(sex, levels = sexes)) |>
  ggplot() +
  geom_point(
    aes(x = rank_2002, y = e0_2002, colour = str_c(sex, ", 2002")),
    size = 0.1,
    alpha = 0.1
  ) +
  geom_point(
    aes(x = rank_2019, y = e0_2019, colour = str_c(sex, ", 2019")),
    size = 0.1,
    alpha = 0.1
  ) +
  geom_smooth(
    aes(x = rank_2002, y = e0_2002, colour = str_c(sex, ", 2002")),
    se = FALSE,
    size = 0.2,
    alpha = 0.8,
    show.legend = FALSE,
    method = "loess"
  ) +
  geom_smooth(
    aes(x = rank_2019, y = e0_2019, colour = str_c(sex, ", 2019")),
    se = FALSE,
    size = 0.2,
    alpha = 0.8,
    show.legend = FALSE,
    method = "loess"
  ) +
  facet_grid(sex ~ IMD, scales = "free_x") +
  scale_colour_manual(
    values = c(
      desaturate(sex_pal[2], amount = 0.5), sex_pal[2],
      desaturate(sex_pal[1], amount = 0.5), sex_pal[1]
    ),
    name = "",
    breaks = str_c(rep(sexes, each = 2), ", ", rep(c(2002, 2019), 2))
  ) +
  guides(colour = guide_legend(override.aes = list(size = 1, alpha = 0.8))) +
  scale_x_continuous(
    breaks = c(n_msoa / 7, 6 * n_msoa / 7),
    labels = c("Least deprived", "Most deprived")
  ) +
  labs(x = "", y = "Life expectancy at birth (years)") +
  theme_thesis() +
  theme(
    legend.key.size = unit(0.01, "npc"),
    legend.position = "top",
    axis.ticks.x = element_blank(),
    strip.text.y = element_blank()
  )

save_plot(
  here(
    "thesis_analysis",
    "england",
    "figures",
    "IMD.pdf"
  ),
  p
)
```
